spring.application.name=devspace

# Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/DevSpace
spring.datasource.username=postgres
spring.datasource.password=devine11

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.open-in-view=false
